/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router

import { createRootRoute } from "@tanstack/react-router";

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";
import { Route as LeaderboardRoute } from "./routes/leaderboard";
import { Route as LiveMatchesRoute } from "./routes/live-matches";
import { Route as MedalTallyRoute } from "./routes/medal-tally";
import { Route as ReportsRoute } from "./routes/reports";
import { Route as ScheduleRoute } from "./routes/schedule";
import { Route as SettingsRoute } from "./routes/settings";
import { Route as SportsSportIdRoute } from "./routes/sports.$sportId";

const rootRouteWithChildren = rootRoute.addChildren([
  IndexRoute,
  LiveMatchesRoute,
  ScheduleRoute,
  LeaderboardRoute,
  MedalTallyRoute,
  ReportsRoute,
  SettingsRoute,
  SportsSportIdRoute,
]);

export const routeTree = rootRouteWithChildren;

export { createRootRoute };
