/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MatchId = IDL.Nat;
export const DalId = IDL.Nat;
export const SportId = IDL.Nat;
export const CreateMatchInput = IDL.Record({
  'dalAId' : DalId,
  'dalBId' : DalId,
  'venue' : IDL.Text,
  'isLive' : IDL.Bool,
  'durationMinutes' : IDL.Nat,
  'sportId' : SportId,
});
export const Timestamp = IDL.Int;
export const MatchStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'live' : IDL.Null,
  'completed' : IDL.Null,
});
export const MatchPublic = IDL.Record({
  'id' : MatchId,
  'startTime' : IDL.Opt(Timestamp),
  'status' : MatchStatus,
  'dalAId' : DalId,
  'dalBId' : DalId,
  'venue' : IDL.Text,
  'scoreA' : IDL.Nat,
  'scoreB' : IDL.Nat,
  'sportName' : IDL.Text,
  'isLive' : IDL.Bool,
  'dalBName' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'elapsedSeconds' : IDL.Nat,
  'sportId' : SportId,
  'dalAName' : IDL.Text,
});
export const Dal = IDL.Record({ 'id' : DalId, 'name' : IDL.Text });
export const LeaderboardEntry = IDL.Record({
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'dalName' : IDL.Text,
  'winPercentage' : IDL.Float64,
  'matchesPlayed' : IDL.Nat,
  'dalId' : DalId,
  'draws' : IDL.Nat,
  'points' : IDL.Nat,
});
export const MedalTallyEntry = IDL.Record({
  'total' : IDL.Nat,
  'bronze' : IDL.Nat,
  'gold' : IDL.Nat,
  'dalName' : IDL.Text,
  'silver' : IDL.Nat,
  'dalId' : DalId,
});
export const SportName = IDL.Text;
export const Sport = IDL.Record({ 'id' : SportId, 'name' : SportName });

export const idlService = IDL.Service({
  'completeMatch' : IDL.Func([MatchId], [IDL.Bool], []),
  'createMatch' : IDL.Func([CreateMatchInput], [IDL.Nat], []),
  'decrementScoreA' : IDL.Func([MatchId], [IDL.Bool], []),
  'decrementScoreB' : IDL.Func([MatchId], [IDL.Bool], []),
  'getAllMatches' : IDL.Func([], [IDL.Vec(MatchPublic)], ['query']),
  'getDals' : IDL.Func([], [IDL.Vec(Dal)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getLeaderboardBySport' : IDL.Func(
      [SportId],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getLiveMatches' : IDL.Func([], [IDL.Vec(MatchPublic)], ['query']),
  'getMatch' : IDL.Func([MatchId], [IDL.Opt(MatchPublic)], ['query']),
  'getMatchStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'scheduled' : IDL.Nat,
          'total' : IDL.Nat,
          'live' : IDL.Nat,
          'completed' : IDL.Nat,
          'todayCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getMatchesBySport' : IDL.Func([SportId], [IDL.Vec(MatchPublic)], ['query']),
  'getMedalTally' : IDL.Func([], [IDL.Vec(MedalTallyEntry)], ['query']),
  'getRecentMatches' : IDL.Func([IDL.Nat], [IDL.Vec(MatchPublic)], ['query']),
  'getSports' : IDL.Func([], [IDL.Vec(Sport)], ['query']),
  'getUpcomingMatches' : IDL.Func([IDL.Nat], [IDL.Vec(MatchPublic)], ['query']),
  'incrementScoreA' : IDL.Func([MatchId], [IDL.Bool], []),
  'incrementScoreB' : IDL.Func([MatchId], [IDL.Bool], []),
  'pauseMatch' : IDL.Func([MatchId], [IDL.Bool], []),
  'resetMatch' : IDL.Func([MatchId], [IDL.Bool], []),
  'setMatchLive' : IDL.Func([MatchId, IDL.Bool], [IDL.Bool], []),
  'startMatch' : IDL.Func([MatchId], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MatchId = IDL.Nat;
  const DalId = IDL.Nat;
  const SportId = IDL.Nat;
  const CreateMatchInput = IDL.Record({
    'dalAId' : DalId,
    'dalBId' : DalId,
    'venue' : IDL.Text,
    'isLive' : IDL.Bool,
    'durationMinutes' : IDL.Nat,
    'sportId' : SportId,
  });
  const Timestamp = IDL.Int;
  const MatchStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'live' : IDL.Null,
    'completed' : IDL.Null,
  });
  const MatchPublic = IDL.Record({
    'id' : MatchId,
    'startTime' : IDL.Opt(Timestamp),
    'status' : MatchStatus,
    'dalAId' : DalId,
    'dalBId' : DalId,
    'venue' : IDL.Text,
    'scoreA' : IDL.Nat,
    'scoreB' : IDL.Nat,
    'sportName' : IDL.Text,
    'isLive' : IDL.Bool,
    'dalBName' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'elapsedSeconds' : IDL.Nat,
    'sportId' : SportId,
    'dalAName' : IDL.Text,
  });
  const Dal = IDL.Record({ 'id' : DalId, 'name' : IDL.Text });
  const LeaderboardEntry = IDL.Record({
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'dalName' : IDL.Text,
    'winPercentage' : IDL.Float64,
    'matchesPlayed' : IDL.Nat,
    'dalId' : DalId,
    'draws' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const MedalTallyEntry = IDL.Record({
    'total' : IDL.Nat,
    'bronze' : IDL.Nat,
    'gold' : IDL.Nat,
    'dalName' : IDL.Text,
    'silver' : IDL.Nat,
    'dalId' : DalId,
  });
  const SportName = IDL.Text;
  const Sport = IDL.Record({ 'id' : SportId, 'name' : SportName });
  
  return IDL.Service({
    'completeMatch' : IDL.Func([MatchId], [IDL.Bool], []),
    'createMatch' : IDL.Func([CreateMatchInput], [IDL.Nat], []),
    'decrementScoreA' : IDL.Func([MatchId], [IDL.Bool], []),
    'decrementScoreB' : IDL.Func([MatchId], [IDL.Bool], []),
    'getAllMatches' : IDL.Func([], [IDL.Vec(MatchPublic)], ['query']),
    'getDals' : IDL.Func([], [IDL.Vec(Dal)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getLeaderboardBySport' : IDL.Func(
        [SportId],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getLiveMatches' : IDL.Func([], [IDL.Vec(MatchPublic)], ['query']),
    'getMatch' : IDL.Func([MatchId], [IDL.Opt(MatchPublic)], ['query']),
    'getMatchStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'scheduled' : IDL.Nat,
            'total' : IDL.Nat,
            'live' : IDL.Nat,
            'completed' : IDL.Nat,
            'todayCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getMatchesBySport' : IDL.Func(
        [SportId],
        [IDL.Vec(MatchPublic)],
        ['query'],
      ),
    'getMedalTally' : IDL.Func([], [IDL.Vec(MedalTallyEntry)], ['query']),
    'getRecentMatches' : IDL.Func([IDL.Nat], [IDL.Vec(MatchPublic)], ['query']),
    'getSports' : IDL.Func([], [IDL.Vec(Sport)], ['query']),
    'getUpcomingMatches' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MatchPublic)],
        ['query'],
      ),
    'incrementScoreA' : IDL.Func([MatchId], [IDL.Bool], []),
    'incrementScoreB' : IDL.Func([MatchId], [IDL.Bool], []),
    'pauseMatch' : IDL.Func([MatchId], [IDL.Bool], []),
    'resetMatch' : IDL.Func([MatchId], [IDL.Bool], []),
    'setMatchLive' : IDL.Func([MatchId, IDL.Bool], [IDL.Bool], []),
    'startMatch' : IDL.Func([MatchId], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };