/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateMatchInput {
  'dalAId' : DalId,
  'dalBId' : DalId,
  'venue' : string,
  'isLive' : boolean,
  'durationMinutes' : bigint,
  'sportId' : SportId,
}
export interface Dal { 'id' : DalId, 'name' : string }
export type DalId = bigint;
export interface LeaderboardEntry {
  'wins' : bigint,
  'losses' : bigint,
  'dalName' : string,
  'winPercentage' : number,
  'matchesPlayed' : bigint,
  'dalId' : DalId,
  'draws' : bigint,
  'points' : bigint,
}
export type MatchId = bigint;
export interface MatchPublic {
  'id' : MatchId,
  'startTime' : [] | [Timestamp],
  'status' : MatchStatus,
  'dalAId' : DalId,
  'dalBId' : DalId,
  'venue' : string,
  'scoreA' : bigint,
  'scoreB' : bigint,
  'sportName' : string,
  'isLive' : boolean,
  'dalBName' : string,
  'durationMinutes' : bigint,
  'elapsedSeconds' : bigint,
  'sportId' : SportId,
  'dalAName' : string,
}
export type MatchStatus = { 'scheduled' : null } |
  { 'live' : null } |
  { 'completed' : null };
export interface MedalTallyEntry {
  'total' : bigint,
  'bronze' : bigint,
  'gold' : bigint,
  'dalName' : string,
  'silver' : bigint,
  'dalId' : DalId,
}
export interface Sport { 'id' : SportId, 'name' : SportName }
export type SportId = bigint;
export type SportName = string;
export type Timestamp = bigint;
export interface _SERVICE {
  'completeMatch' : ActorMethod<[MatchId], boolean>,
  'createMatch' : ActorMethod<[CreateMatchInput], bigint>,
  'decrementScoreA' : ActorMethod<[MatchId], boolean>,
  'decrementScoreB' : ActorMethod<[MatchId], boolean>,
  'getAllMatches' : ActorMethod<[], Array<MatchPublic>>,
  'getDals' : ActorMethod<[], Array<Dal>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getLeaderboardBySport' : ActorMethod<[SportId], Array<LeaderboardEntry>>,
  'getLiveMatches' : ActorMethod<[], Array<MatchPublic>>,
  'getMatch' : ActorMethod<[MatchId], [] | [MatchPublic]>,
  'getMatchStats' : ActorMethod<
    [],
    {
      'scheduled' : bigint,
      'total' : bigint,
      'live' : bigint,
      'completed' : bigint,
      'todayCount' : bigint,
    }
  >,
  'getMatchesBySport' : ActorMethod<[SportId], Array<MatchPublic>>,
  'getMedalTally' : ActorMethod<[], Array<MedalTallyEntry>>,
  'getRecentMatches' : ActorMethod<[bigint], Array<MatchPublic>>,
  'getSports' : ActorMethod<[], Array<Sport>>,
  'getUpcomingMatches' : ActorMethod<[bigint], Array<MatchPublic>>,
  'incrementScoreA' : ActorMethod<[MatchId], boolean>,
  'incrementScoreB' : ActorMethod<[MatchId], boolean>,
  'pauseMatch' : ActorMethod<[MatchId], boolean>,
  'resetMatch' : ActorMethod<[MatchId], boolean>,
  'setMatchLive' : ActorMethod<[MatchId, boolean], boolean>,
  'startMatch' : ActorMethod<[MatchId], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];