/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    wins: bigint;
    losses: bigint;
    dalName: string;
    winPercentage: number;
    matchesPlayed: bigint;
    dalId: DalId;
    draws: bigint;
    points: bigint;
}
export type Timestamp = bigint;
export interface Sport {
    id: SportId;
    name: SportName;
}
export type SportId = bigint;
export type DalId = bigint;
export interface MatchPublic {
    id: MatchId;
    startTime?: Timestamp;
    status: MatchStatus;
    dalAId: DalId;
    dalBId: DalId;
    venue: string;
    scoreA: bigint;
    scoreB: bigint;
    sportName: string;
    isLive: boolean;
    dalBName: string;
    durationMinutes: bigint;
    elapsedSeconds: bigint;
    sportId: SportId;
    dalAName: string;
}
export interface Dal {
    id: DalId;
    name: string;
}
export interface CreateMatchInput {
    dalAId: DalId;
    dalBId: DalId;
    venue: string;
    isLive: boolean;
    durationMinutes: bigint;
    sportId: SportId;
}
export type SportName = string;
export interface MedalTallyEntry {
    total: bigint;
    bronze: bigint;
    gold: bigint;
    dalName: string;
    silver: bigint;
    dalId: DalId;
}
export type MatchId = bigint;
export enum MatchStatus {
    scheduled = "scheduled",
    live = "live",
    completed = "completed"
}
export interface backendInterface {
    completeMatch(matchId: MatchId): Promise<boolean>;
    createMatch(input: CreateMatchInput): Promise<bigint>;
    decrementScoreA(matchId: MatchId): Promise<boolean>;
    decrementScoreB(matchId: MatchId): Promise<boolean>;
    getAllMatches(): Promise<Array<MatchPublic>>;
    getDals(): Promise<Array<Dal>>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getLeaderboardBySport(sportId: SportId): Promise<Array<LeaderboardEntry>>;
    getLiveMatches(): Promise<Array<MatchPublic>>;
    getMatch(id: MatchId): Promise<MatchPublic | null>;
    getMatchStats(): Promise<{
        scheduled: bigint;
        total: bigint;
        live: bigint;
        completed: bigint;
        todayCount: bigint;
    }>;
    getMatchesBySport(sportId: SportId): Promise<Array<MatchPublic>>;
    getMedalTally(): Promise<Array<MedalTallyEntry>>;
    getRecentMatches(limit: bigint): Promise<Array<MatchPublic>>;
    getSports(): Promise<Array<Sport>>;
    getUpcomingMatches(limit: bigint): Promise<Array<MatchPublic>>;
    incrementScoreA(matchId: MatchId): Promise<boolean>;
    incrementScoreB(matchId: MatchId): Promise<boolean>;
    pauseMatch(matchId: MatchId): Promise<boolean>;
    resetMatch(matchId: MatchId): Promise<boolean>;
    setMatchLive(matchId: MatchId, isLive: boolean): Promise<boolean>;
    startMatch(matchId: MatchId): Promise<boolean>;
}
import type { DalId as _DalId, MatchId as _MatchId, MatchPublic as _MatchPublic, MatchStatus as _MatchStatus, SportId as _SportId, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async completeMatch(arg0: MatchId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeMatch(arg0);
            return result;
        }
    }
    async createMatch(arg0: CreateMatchInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(arg0);
            return result;
        }
    }
    async decrementScoreA(arg0: MatchId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.decrementScoreA(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.decrementScoreA(arg0);
            return result;
        }
    }
    async decrementScoreB(arg0: MatchId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.decrementScoreB(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.decrementScoreB(arg0);
            return result;
        }
    }
    async getAllMatches(): Promise<Array<MatchPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatches();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatches();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDals(): Promise<Array<Dal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDals();
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getLeaderboardBySport(arg0: SportId): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboardBySport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboardBySport(arg0);
            return result;
        }
    }
    async getLiveMatches(): Promise<Array<MatchPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveMatches();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveMatches();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatch(arg0: MatchId): Promise<MatchPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchStats(): Promise<{
        scheduled: bigint;
        total: bigint;
        live: bigint;
        completed: bigint;
        todayCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchStats();
            return result;
        }
    }
    async getMatchesBySport(arg0: SportId): Promise<Array<MatchPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchesBySport(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchesBySport(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMedalTally(): Promise<Array<MedalTallyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedalTally();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedalTally();
            return result;
        }
    }
    async getRecentMatches(arg0: bigint): Promise<Array<MatchPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentMatches(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentMatches(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSports(): Promise<Array<Sport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSports();
            return result;
        }
    }
    async getUpcomingMatches(arg0: bigint): Promise<Array<MatchPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingMatches(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingMatches(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementScoreA(arg0: MatchId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementScoreA(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementScoreA(arg0);
            return result;
        }
    }
    async incrementScoreB(arg0: MatchId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementScoreB(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementScoreB(arg0);
            return result;
        }
    }
    async pauseMatch(arg0: MatchId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.pauseMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pauseMatch(arg0);
            return result;
        }
    }
    async resetMatch(arg0: MatchId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.resetMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetMatch(arg0);
            return result;
        }
    }
    async setMatchLive(arg0: MatchId, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setMatchLive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMatchLive(arg0, arg1);
            return result;
        }
    }
    async startMatch(arg0: MatchId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.startMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startMatch(arg0);
            return result;
        }
    }
}
function from_candid_MatchPublic_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchPublic): MatchPublic {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchPublic]): MatchPublic | null {
    return value.length === 0 ? null : from_candid_MatchPublic_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MatchId;
    startTime: [] | [_Timestamp];
    status: _MatchStatus;
    dalAId: _DalId;
    dalBId: _DalId;
    venue: string;
    scoreA: bigint;
    scoreB: bigint;
    sportName: string;
    isLive: boolean;
    dalBName: string;
    durationMinutes: bigint;
    elapsedSeconds: bigint;
    sportId: _SportId;
    dalAName: string;
}): {
    id: MatchId;
    startTime?: Timestamp;
    status: MatchStatus;
    dalAId: DalId;
    dalBId: DalId;
    venue: string;
    scoreA: bigint;
    scoreB: bigint;
    sportName: string;
    isLive: boolean;
    dalBName: string;
    durationMinutes: bigint;
    elapsedSeconds: bigint;
    sportId: SportId;
    dalAName: string;
} {
    return {
        id: value.id,
        startTime: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.startTime)),
        status: from_candid_MatchStatus_n5(_uploadFile, _downloadFile, value.status),
        dalAId: value.dalAId,
        dalBId: value.dalBId,
        venue: value.venue,
        scoreA: value.scoreA,
        scoreB: value.scoreB,
        sportName: value.sportName,
        isLive: value.isLive,
        dalBName: value.dalBName,
        durationMinutes: value.durationMinutes,
        elapsedSeconds: value.elapsedSeconds,
        sportId: value.sportId,
        dalAName: value.dalAName
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    live: null;
} | {
    completed: null;
}): MatchStatus {
    return "scheduled" in value ? MatchStatus.scheduled : "live" in value ? MatchStatus.live : "completed" in value ? MatchStatus.completed : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MatchPublic>): Array<MatchPublic> {
    return value.map((x)=>from_candid_MatchPublic_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
